route: /arbitrum
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://arb1.arbitrum.io/rpc
    priority: 1
  - url: https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    priority: 3
    headers:
      Content-Type: application/json

