route: /aurora
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://mainnet.aurora.dev
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://1rpc.io/aurora
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://aurora-mainnet.gateway.tatum.io/
    priority: 2
    headers:
      accept: application/json
      content-type: application/json
      x-api-key: ${TATUM_API_KEY}
