route: /aurora
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://mainnet.aurora.dev
    isPrivate: false
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://1rpc.io/aurora
    isPrivate: false
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://aurora-mainnet.gateway.tatum.io/
    isPrivate: true
    priority: 2
    headers:
      accept: application/json
      content-type: application/json
      x-api-key: ${TATUM_API_KEY}
  - url: https://aurora-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    isPrivate: true
    priority: 3
    headers:
      Content-Type: application/json
