route: /bsc
protocol: evm
timeoutMs: 2000
nodes:
  - url: https://bsc-dataseed.binance.org
    priority: 1
  - url: https://bsc-mainnet.gateway.tatum.io
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
  - url: https://bsc-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    priority: 3
    headers:
      Content-Type: application/json
