route: /rpc/btc
protocol: btc
nodes:
  - url: https://blockstream.info/api
    priority: 1
  - url: https://bitcoin-mainnet.gateway.tatum.io
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
# при наличии onion-ноды:
#  - url: http://btcnodeexample.onion
#    priority: 1
#    tor: true
