route: /cro
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://evm.cronos.org
    isPrivate: false
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://cronos-mainnet.gateway.tatum.io/
    isPrivate: true
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
  - url: https://cronos-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    isPrivate: true
    priority: 3
    headers:
      Content-Type: application/json

