route: /eth
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://eth.llamarpc.com
    priority: 1
    isPrivate: false
  - url: https://gateway.tenderly.co/public/mainnet
    isPrivate: false
    priority: 1
  - url: https://ethereum.blockpi.network/v1/rpc/public
    isPrivate: false
    priority: 1
  - url: https://1rpc.io/eth
    isPrivate: false
    priority: 1
  - url: https://eth-pokt.nodies.app
    isPrivate: false
    priority: 1
  - url: https://rpc.payload.de
    isPrivate: false
    priority: 1
  - url: https://ethereum-rpc.publicnode.com
    isPrivate: false
    priority: 1
  - url: https://eth.drpc.org
    isPrivate: false
    priority: 1

  - url: https://ethereum-mainnet.gateway.tatum.io/
    priority: 2
    isPrivate: true
    headers:
      content-type: application/json
      x-api-key: ${TATUM_API_KEY}

  - url: https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}
    priority: 3
    isPrivate: true
    headers:
      Content-Type: application/json

