route: /iotx
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://babel-api.mainnet.iotex.io
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://iotex-mainnet.gateway.tatum.io/
    priority: 2
    headers:
      accept: application/json
      content-type: application/json
      x-api-key: ${TATUM_API_KEY}
