route: /rpc/klay
protocol: evm
nodes:
  - url: https://1rpc.io/klay
    isPrivate: false
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://klaytn-mainnet.gateway.tatum.io/
    isPrivate: true
    priority: 2
    headers:
      accept: application/json
      content-type: application/json
      x-api-key: ${TATUM_API_KEY}
