route: /ltc
protocol: ltc
timeoutMs: 1500
nodes:
  - url: https://litecoinblockexplorer.net/api
    priority: 1
  - url: https://litecoin-mainnet.gateway.tatum.io
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
