route: /moonbeam
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://rpc.api.moonbeam.network
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://moonbeam-mainnet.gateway.tatum.io/
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
