route: /rpc/moonbeam
protocol: evm
nodes:
  - url: https://rpc.api.moonbeam.network
    isPrivate: false
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://moonbeam-mainnet.gateway.tatum.io/
    isPrivate: true
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
