route: /nft
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://eth.llamarpc.com
    priority: 1
    isPrivate: false

  - url: https://ethereum-mainnet.gateway.tatum.io/
    priority: 2
    isPrivate: true
    headers:
     x-api-key: ${TATUM_API_KEY}
