route: /oasis
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://emerald.oasis.dev
    isPrivate: false
    priority: 1
    headers:
      Content-Type: application/json
  - url: https://oasis-mainnet.gateway.tatum.io/
    isPrivate: true
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
