route: /rpc/optimism
protocol: evm
nodes:
  - url: https://mainnet.optimism.io
    priority: 1
  - url: https://optimism-mainnet.gateway.tatum.io
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
