route: /polygon
protocol: evm
timeoutMs: 1500
nodes:
  - url: https://polygon-rpc.com
    priority: 1
  - url: https://polygon-mainnet.gateway.tatum.io
    priority: 2
    headers:
      x-api-key: ${TATUM_API_KEY}
